.PHONY: 1a 1b 2a 2b 3a 3b test3a test3b

1a:
	day_1/day1a.rkt < day_1/input.txt
1b:
	day_1/day1b.rkt < day_1/input.txt
test1b:
	day_1/day1b.rkt < day_1/testinput.txt

2a:
	day_2/day2a.rkt < day_2/input.txt
2b:
	day_2/day2b.rkt < day_2/input.txt

3a:
	julia day_3/day3a.jl < day_3/input.txt
test3a:
	julia day_3/day3a.jl < day_3/test_input.txt
3b:
	julia day_3/day3b.jl < day_3/input.txt
test3b:
	julia day_3/day3b.jl < day_3/test_input.txt